/**
 * Identifier helpers.
 *
 * All persisted ids are UUIDs generated by the database by default; these
 * helpers exist for records created in application code before they are
 * written, and for correlation ids that tie a chain of events together.
 */

export function newId(): string {
  return crypto.randomUUID();
}

/**
 * A correlation id groups every event, task, approval and audit entry produced
 * by one causal chain — e.g. a trade fill and the journal entry, analysis and
 * notification it triggered. Without this, reconstructing "why did Jarvis do
 * that?" months later is guesswork.
 */
export function newCorrelationId(): string {
  return crypto.randomUUID();
}

export function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}
