import type { Domain, ReadinessLevel } from "@/core/types";

/**
 * World State is Jarvis's structured understanding of what is currently true.
 *
 * It is explicitly NOT a prose summary generated by a model. A blob of text
 * cannot be diffed, cannot be charted, and cannot be checked for staleness —
 * and a system that reasons about money needs all three. Narrative is produced
 * *from* this structure at the edge, never stored in place of it.
 */

/**
 * How much the numbers in a slice can be trusted. Surfaced in the UI, because
 * a stale finance panel and a live one look identical otherwise — and during
 * v0.1 everything is `mock`.
 */
export const dataQualities = ["live", "stale", "mock", "unavailable"] as const;
export type DataQuality = (typeof dataQualities)[number];

export const metricFormats = ["currency", "percent", "number", "r_multiple", "duration", "text"] as const;
export type MetricFormat = (typeof metricFormats)[number];

/** Direction that counts as improvement, so the UI can colour a delta correctly. */
export const metricPolarities = ["higher_is_better", "lower_is_better", "neutral"] as const;
export type MetricPolarity = (typeof metricPolarities)[number];

export interface Metric {
  readonly key: string;
  readonly label: string;
  /** Currency values are minor units. Percent values are 0..1 fractions. */
  readonly value: number | string;
  readonly format: MetricFormat;
  readonly polarity?: MetricPolarity;
  /** Change since the previous comparable period, in the same unit as `value`. */
  readonly delta?: number;
  readonly caption?: string;
}

/** One domain's answer to "what is happening?". */
export interface WorldStateSlice {
  readonly domain: Domain;
  /** One line, suitable for display as-is. No model call required to produce it. */
  readonly headline: string;
  /** Domain-level status, when the domain has a meaningful rollup. */
  readiness?: ReadinessLevel;
  readonly metrics: readonly Metric[];
  /** Short machine-readable status tags, e.g. `learning`, `market_open`. */
  readonly flags?: readonly string[];
  readonly dataQuality: DataQuality;
  readonly observedAt: string;
}

export interface WorldState {
  readonly userId: string;
  readonly capturedAt: string;
  readonly slices: Readonly<Partial<Record<Domain, WorldStateSlice>>>;
}

/**
 * A persisted point-in-time copy. Snapshots are how "what changed since
 * Tuesday?" becomes answerable — the live view alone can only say what is true
 * right now.
 */
export interface WorldStateSnapshot {
  readonly id: string;
  readonly userId: string;
  readonly capturedAt: string;
  /** `scheduled`, `manual`, or the event type that triggered the capture. */
  readonly reason: string;
  readonly state: WorldState;
}
