import { FEATURES, PINE_BLOCKS, type PineBlock } from "./features.ts";
import type { SignalPolicy } from "./evaluate.ts";
import type { EvaluationMetrics, Rule } from "./types.ts";

const BLOCK_ORDER: PineBlock[] = ["core", "hma", "htf60", "htf240", "daily", "session", "bank"];

function num(value: number) {
  if (!Number.isFinite(value)) return "0";
  const fixed = Math.abs(value) >= 100 ? value.toFixed(0) : Number(value.toPrecision(4)).toString();
  return fixed.includes("e") ? value.toFixed(6) : fixed;
}

function pct(value: number) {
  return (value * 100).toFixed(0) + "%";
}

function describe(m: EvaluationMetrics | null) {
  if (!m) return "n/a";
  return `recall ${pct(m.combined.recall)} · agreement ${pct(m.combined.precision)} · ${m.combined.signalsPerDay.toFixed(2)} arrows/day · avg ${m.combined.avgR == null ? "n/a" : m.combined.avgR.toFixed(2) + "R"}`;
}

export function generatePine(input: {
  version: string;
  rules: Rule[];
  policy: SignalPolicy;
  generatedAt: string;
  trainEntries: number;
  sessions: number;
  test: EvaluationMetrics | null;
  baselineTest: EvaluationMetrics | null;
}): string {
  const used = new Set(input.rules.flatMap((rule) => rule.conditions.map((c) => c.feature)));
  const specs = FEATURES.filter((f) => used.has(f.name));
  const blocks = new Set<PineBlock>(["core"]);
  for (const spec of specs) for (const block of spec.needs) blocks.add(block);

  const ruleLines: string[] = [];
  const names: Record<"LONG" | "SHORT", string[]> = { LONG: [], SHORT: [] };
  input.rules.forEach((rule, index) => {
    const name = `${rule.side === "LONG" ? "long" : "short"}_rule_${index + 1}`;
    names[rule.side].push(name);
    const expr = rule.conditions.map((c) => `f_${c.feature} ${c.op} ${num(c.value)}`).join(" and ") || "false";
    ruleLines.push(`// ${rule.side} · train precision ${pct(rule.trainPrecision)} over ${rule.trainSupport} matches`);
    ruleLines.push(`${name} = ${expr}`);
  });

  const lines = [
    "//@version=6",
    `indicator("DEVIANT - LEARNED ${input.version}", overlay=true, max_bars_back=500)`,
    "",
    `// Generated by the JARVIS learning pipeline on ${input.generatedAt}. Regenerate instead of editing by hand.`,
    "// Baseline trading/indicators/deviant-refined-baseline-v1.pine is untouched; this is a separate candidate.",
    `// Learned from ${input.trainEntries} of Dwight's observed entries across ${input.sessions} sessions.`,
    `// Held-out test: ${describe(input.test)}`,
    `// DEVIANT v1 on the same test: ${describe(input.baselineTest)}`,
    "// Visual contract: entry arrows only — buy arrows blue, sell arrows black.",
    "",
    `max_arrows = input.int(${input.policy.maxPerDay}, "Max arrows per day", minval = 1)`,
    `cooldown = input.int(${input.policy.cooldownBars}, "Cooldown bars after an arrow", minval = 0)`,
    `win_start = input.int(${input.policy.startMinute}, "Window start (New York minute of day)")`,
    `win_end = input.int(${input.policy.endMinute}, "Window end (New York minute of day)")`,
    `webhook_secret = input.string("", "JARVIS shadow webhook secret (optional)")`,
    "",
    ...BLOCK_ORDER.filter((b) => blocks.has(b)).map((b) => PINE_BLOCKS[b]),
    "",
    ...specs.map((spec) => spec.pine),
    "",
    ...ruleLines,
    "",
    `long_ok = ${names.LONG.length ? names.LONG.join(" or ") : "false"}`,
    `short_ok = ${names.SHORT.length ? names.SHORT.join(" or ") : "false"}`,
    "",
    "var int day_count = 0",
    "var int last_long = -100000",
    "var int last_short = -100000",
    'if ta.change(time("D")) != 0',
    "    day_count := 0",
    "in_window = ny_min >= win_start and ny_min <= win_end",
    "long_signal = barstate.isconfirmed and in_window and long_ok and day_count < max_arrows and bar_index - last_long > cooldown",
    "if long_signal",
    "    day_count += 1",
    "    last_long := bar_index",
    "short_signal = barstate.isconfirmed and in_window and short_ok and day_count < max_arrows and bar_index - last_short > cooldown",
    "if short_signal",
    "    day_count += 1",
    "    last_short := bar_index",
    "",
    'plotshape(long_signal, "BUY", shape.triangleup, location.belowbar, color.new(color.blue, 0), size = size.small)',
    'plotshape(short_signal, "SELL", shape.triangledown, location.abovebar, color.new(color.black, 0), size = size.small)',
    "",
    `alertcondition(long_signal, "DEVIANT LEARNED BUY", "DEVIANT ${input.version} BUY")`,
    `alertcondition(short_signal, "DEVIANT LEARNED SELL", "DEVIANT ${input.version} SELL")`,
    "",
    "// Shadow scoring: create ONE alert on this indicator with \"Any alert() function call\" and the",
    "// JARVIS webhook URL (/api/trading/market-webhook). JARVIS compares these arrows with your trades.",
    "f_signal_json(side) =>",
    `    '{"secret":"' + webhook_secret + '","kind":"signal","model":"${input.version}","symbol":"' + syminfo.ticker + '","side":"' + side + '","time":' + str.tostring(time) + ',"price":' + str.tostring(close) + '}'`,
    "if long_signal and str.length(webhook_secret) > 0",
    '    alert(f_signal_json("LONG"), alert.freq_once_per_bar_close)',
    "if short_signal and str.length(webhook_secret) > 0",
    '    alert(f_signal_json("SHORT"), alert.freq_once_per_bar_close)',
    "",
  ];
  return lines.join("\n");
}
