"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, BookOpen, BriefcaseBusiness, Check, ChevronRight, Compass, Cross, Dumbbell, Focus, HeartHandshake, Plus, Shield, Sparkles, Target, Timer, WalletCards, X } from "lucide-react";
import { DAY_BLOCKS, emptyLifePlan, LIFE_PLAN_KEY, LifeDay, LifePlan, loadLifePlan, localDay, newLifeDay, REFLECTIONS, reflectionIndex } from "../lib/life-plan";
import { Mission, MissionIdea, MISSIONS, Pillar, PILLARS, PLACES, LocalPlace, recentDays, weeklyPillarDays } from "../lib/life-missions";
import styles from "./life-cockpit.module.css";

const ICONS = {empire:BriefcaseBusiness,money:WalletCards,body:Dumbbell,mind:BookOpen,faith:Cross,presence:Shield,relationships:HeartHandshake,experiences:Compass};
const VIEWS = ['TODAY','BUILD','EXPLORE','REVIEW'] as const;
type View = typeof VIEWS[number];

export function LifeProgress() {
  const [plan,setPlan]=useState<LifePlan|null>(null);
  const [date,setDate]=useState('');
  useEffect(()=>{const refresh=()=>{try{setPlan(loadLifePlan());setDate(localDay());}catch{setPlan(null);}};refresh();const timer=window.setInterval(refresh,60_000);window.addEventListener('jarvis-life-updated',refresh);window.addEventListener('storage',refresh);return()=>{window.clearInterval(timer);window.removeEventListener('jarvis-life-updated',refresh);window.removeEventListener('storage',refresh);};},[]);
  return <div className={styles.rail}><div className={styles.railIntro}>DEVELOPMENT / SAME LIVE 7D PROGRESS AS LIFE</div>{PILLARS.map(p=>{const Icon=ICONS[p.id];const count=plan?weeklyPillarDays(plan.missions,date,p.id):0;const percent=plan?Math.min(100,Math.round(count/p.target*100)):0;return <div className={styles.railItem} key={p.id}><div><Icon size={13}/><span>{p.label}</span><b>{plan?`${percent}%`:'—'}<small> · {count}/{p.target}</small></b></div><div className={styles.bar}><i style={{width:`${percent}%`}}/></div></div>;})}<p>These percentages are driven by the same completed Life missions shown on the Life page.</p></div>;
}

export default function LifeCockpit() {
  const [plan,setPlan]=useState<LifePlan>(emptyLifePlan);
  const [ready,setReady]=useState(false);
  const [error,setError]=useState('');
  const [now,setNow]=useState(0);
  const [view,setView]=useState<View>('TODAY');
  const [pillar,setPillar]=useState<Pillar>('empire');
  const [available,setAvailable]=useState(60);
  const [reset,setReset]=useState(false);
  const [trigger,setTrigger]=useState('Scrolling');
  const [notice,setNotice]=useState('');
  const [editPriorities,setEditPriorities]=useState(false);
  const [custom,setCustom]=useState('');
  const [customMinutes,setCustomMinutes]=useState(25);
  const [outing,setOuting]=useState<LocalPlace|null>(null);
  const [outingDate,setOutingDate]=useState('');
  const [outingTime,setOutingTime]=useState('');
  const [kind,setKind]=useState('All types');
  const [focusTitle,setFocusTitle]=useState('');
  const [focusLength,setFocusLength]=useState(25);
  const [expanded,setExpanded]=useState<string|null>(null);
  const [removed,setRemoved]=useState<Mission|null>(null);
  const focusRef=useRef<HTMLElement>(null);
  const topRef=useRef<HTMLDivElement>(null);

  useEffect(()=>{const refresh=()=>{try{setPlan(loadLifePlan());setError('');setReady(true);}catch{setError('Could not load your saved Life history. Reload before editing; your history has not been replaced.');setReady(false);}setNow(Date.now());};refresh();const timer=window.setInterval(()=>setNow(Date.now()),1000);const sync=(e:StorageEvent)=>{if(e.key===LIFE_PLAN_KEY||e.key===null)refresh();};window.addEventListener('storage',sync);window.addEventListener('focus',refresh);return()=>{window.clearInterval(timer);window.removeEventListener('storage',sync);window.removeEventListener('focus',refresh);};},[]);
  function update(change:(current:LifePlan)=>LifePlan) {try{const next=change(loadLifePlan());window.localStorage.setItem(LIFE_PLAN_KEY,JSON.stringify(next));setPlan(next);setError('');window.dispatchEvent(new Event('jarvis-life-updated'));return true;}catch{setError('Could not save this change. Check browser storage and try again; your previous history is kept.');return false;}}
  function changeDay(change:(day:LifeDay)=>LifeDay){const key=localDay();return update(current=>({...current,days:{...current.days,[key]:change(current.days[key]||newLifeDay())}}));}
  const date=now?localDay(new Date(now)):'';
  const day=plan.days[date]||newLifeDay();
  const intelligenceIndex=day.intelligenceIndex ?? (reflectionIndex(date)%REFLECTIONS.length);
  const quote=REFLECTIONS[intelligenceIndex];
  const todayMissions=plan.missions.filter(m=>m.date===date).sort((a,b)=>Number(a.done)-Number(b.done)||a.time.localeCompare(b.time));
  const upcoming=plan.missions.filter(m=>m.date>date).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));
  const overdue=plan.missions.filter(m=>m.date<date&&!m.done);
  const dates=recentDays(date||localDay());
  const weekDone=plan.missions.filter(m=>m.done&&dates.includes(m.completedOn||m.date));
  const coverage=new Set(weekDone.map(m=>m.pillar)).size;
  const nextPriority=day.priorities.find(p=>!p.done);
  const nextMission=todayMissions.find(m=>!m.done);
  const nextTitle=nextMission?.title||nextPriority?.title||'Choose your next mission or take planned rest.';
  const remaining=plan.session?Math.max(0,Math.ceil((plan.session.endsAt-now)/1000)):0;
  const selected=PILLARS.find(p=>p.id===pillar)!;
  const suggested=MISSIONS.filter(m=>m.pillar===pillar&&m.minutes<=available);

  useEffect(()=>{if(!ready||!date||day.intelligenceIndex!==undefined)return;changeDay(d=>({...d,intelligenceIndex:reflectionIndex(date)%REFLECTIONS.length}));},[ready,date,day.intelligenceIndex]);

  function addMission(idea:MissionIdea,dateToUse=localDay(),time='',sourceId=idea.id){let duplicate=false;const mission:Mission={id:crypto.randomUUID(),sourceId,pillar:idea.pillar,title:idea.title,detail:idea.detail,minutes:idea.minutes,date:dateToUse,time,done:false,evidence:''};const ok=update(current=>{if(current.missions.some(m=>m.sourceId===sourceId&&m.date===dateToUse)){duplicate=true;return current;}return {...current,missions:[...current.missions,mission]};});if(ok)setNotice(duplicate?'Already on that day’s plan.':`Added: ${idea.title} · ${dateToUse}${time?' at '+time:''}`);return ok;}
  function patchMission(id:string,patch:Partial<Mission>){return update(current=>({...current,missions:current.missions.map(m=>m.id===id?{...m,...patch}:m)}));}
  function startFocus(title:string,duration:number){let occupied=false;const ok=update(current=>{if(current.session){occupied=true;return current;}return {...current,session:{title,minutes:duration,endsAt:Date.now()+duration*60_000,day:localDay()}};});if(ok){setNotice(occupied?'Finish or cancel the current block first.':'Focus started. One task. Phone out of reach.');focusRef.current?.scrollIntoView({behavior:'smooth',block:'center'});}}
  function endFocus(record:boolean){const ok=update(current=>{const s=current.session;if(!s||(record&&s.endsAt>Date.now()))return current;const target=current.days[s.day]||newLifeDay();return {...current,session:null,days:record?{...current.days,[s.day]:{...target,focusMinutes:target.focusMinutes+s.minutes}}:current.days};});if(ok)setNotice(record?'Focused time recorded. Mark your mission complete when its result is finished.':'Timer cancelled. Choose your next step.');}
  function openView(next:View){setView(next);topRef.current?.scrollIntoView({behavior:'smooth',block:'start'});}
  function missionRow(m:Mission){const Icon=ICONS[m.pillar];return <article className={`${styles.mission} ${m.done?styles.done:''}`} key={m.id}><div className={styles.missionMain}><button className={styles.check} aria-label={`${m.done?'Undo':'Complete'} ${m.title}`} aria-pressed={m.done} onClick={()=>patchMission(m.id,{done:!m.done,completedOn:m.done?undefined:localDay()})}>{m.done?<Check size={15}/>:<span/>}</button><button className={styles.missionTitle} aria-expanded={expanded===m.id} onClick={()=>setExpanded(expanded===m.id?null:m.id)}><span><Icon size={12}/>{PILLARS.find(p=>p.id===m.pillar)?.label} · {m.time||'FLEXIBLE'} · {m.minutes} MIN</span><strong>{m.title}</strong></button>{!m.done&&<button className={styles.iconButton} aria-label={`Focus on ${m.title}`} disabled={!!plan.session} onClick={()=>startFocus(m.title,m.minutes)}><Focus size={16}/></button>}</div>{expanded===m.id&&<div className={styles.missionDetail}><p>{m.detail}</p><label>Result / what I learned<textarea rows={2} maxLength={1000} value={m.evidence} onChange={e=>patchMission(m.id,{evidence:e.target.value})}/></label><div className={styles.controls}><label>Date<input type="date" value={m.date} onChange={e=>{if(e.target.value)patchMission(m.id,{date:e.target.value});}}/></label><label>Time<input type="time" value={m.time} onChange={e=>patchMission(m.id,{time:e.target.value})}/></label><button onClick={()=>{if(update(current=>({...current,missions:current.missions.filter(item=>item.id!==m.id)}))){setRemoved(m);setNotice('Mission removed. You can undo this below.');}}}>Remove</button></div></div>}</article>;}

  return <div className={styles.life} ref={topRef} aria-label="Don Life command">
    <header className={styles.header}><div><span className={styles.kicker}><Target size={13}/> JARVIS / PERSONAL DEVELOPMENT</span><h2>THE DON</h2><p>Build your empire. Develop the man. Keep God first.</p></div><button className={styles.resetButton} onClick={()=>setReset(!reset)} aria-expanded={reset}><Shield size={14}/> RESET</button></header>
    <div className={styles.metrics}><div><span>PRIORITIES TODAY</span><b>{day.priorities.filter(p=>p.done).length}<small> / {day.priorities.length}</small></b></div><div><span>FOCUSED TODAY</span><b>{day.focusMinutes}<small> MIN</small></b></div><div><span>MISSIONS / 7D</span><b>{weekDone.length}</b></div><div><span>AREAS BUILT / 7D</span><b>{coverage}<small> / 8</small></b></div></div>
    <nav className={styles.tabs} aria-label="Life views">{VIEWS.map(v=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>setView(v)}>{v==='TODAY'?<Target size={13}/>:v==='BUILD'?<BriefcaseBusiness size={13}/>:v==='EXPLORE'?<Compass size={13}/>:<BookOpen size={13}/>} {v}</button>)}</nav>
    {error&&<p role="alert" className={styles.error}>{error}</p>}
    {notice&&<div role="status" className={styles.notice}>{notice}{removed&&<button onClick={()=>{if(update(current=>({...current,missions:current.missions.some(m=>m.id===removed.id)?current.missions:[...current.missions,removed]}))){setRemoved(null);setNotice('Mission restored.');}}}>Undo removal</button>}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={13}/></button></div>}
    {!ready?<p>Loading your saved plan…</p>:<>
      {reset&&<section className={styles.resetPanel}><div className={styles.panelHead}><h3>BREAK THE LOOP</h3><button aria-label="Close reset" onClick={()=>setReset(false)}><X size={14}/></button></div><label>What pulled you off course?<select value={trigger} onChange={e=>setTrigger(e.target.value)}>{['Scrolling','Netflix','Vaping','Porn or sexual urge','Boredom','Avoiding a task'].map(t=><option key={t}>{t}</option>)}</select></label><div className={styles.resetSteps}><p><b>01 / MOVE</b> Stand up and change rooms.</p><p><b>02 / REMOVE</b> {trigger==='Vaping'?'Put the disposable out of reach.':'Close the content and put the phone away.'}</p><p><b>03 / RECOMMIT</b> Pray, name what you need, and choose one five-minute action.</p></div><button disabled={!!plan.session} onClick={()=>startFocus('Clear my space and choose my next action',5)}>START 5-MINUTE RESET <ChevronRight size={14}/></button><small>Your trigger choice is not saved. Urges do not erase progress; choose the next action.</small></section>}
      {view==='TODAY'&&<>
        <div className={styles.todayGrid}><section className={styles.panel}><div className={styles.panelHead}><h3>DAILY ORDERS</h3><div className={styles.orderActions}><button aria-label="Add daily order" disabled={day.priorities.length>=20} onClick={()=>changeDay(d=>({...d,priorities:[...d.priorities,{title:'New daily order',done:false}]}))}><Plus size={13}/> ADD</button><button onClick={()=>setEditPriorities(!editPriorities)}>{editPriorities?'DONE EDITING':'EDIT'}</button></div></div><div className={styles.priorities}>{day.priorities.map((p,i)=><div className={styles.priority} key={i}><label className={styles.priorityCheck}><input type="checkbox" checked={p.done} aria-label={`Complete priority ${i+1}`} onChange={()=>changeDay(d=>({...d,priorities:d.priorities.map((item,n)=>n===i?{...item,done:!item.done}:item)}))}/><span>{String(i+1).padStart(2,'0')}</span></label>{editPriorities?<><input aria-label={`Priority ${i+1}`} maxLength={180} value={p.title} onChange={e=>{const title=e.target.value;changeDay(d=>({...d,priorities:d.priorities.map((item,n)=>n===i?{...item,title}:item)}));}}/>{day.priorities.length>1?<button className={styles.priorityRemove} aria-label={`Remove priority ${i+1}`} onClick={()=>changeDay(d=>({...d,priorities:d.priorities.filter((_,n)=>n!==i)}))}><X size={12}/></button>:null}</>:<p className={p.done?styles.strike:''}>{p.title}</p>}</div>)}</div><div className={styles.next}><span>NEXT MOVE</span><strong>{nextTitle}</strong><button disabled={!!plan.session||(!nextMission&&!nextPriority)} onClick={()=>startFocus(nextTitle,nextMission?.minutes||25)}>ENGAGE FOCUS <ArrowUpRight size={14}/></button></div></section><section className={`${styles.panel} ${styles.brief}`}><div className={styles.panelHead}><h3>DAILY INTELLIGENCE</h3><Cross size={14}/></div><span className={styles.kicker}>QUOTE / JARVIS ORIGINAL</span><blockquote>“{quote[0]}”</blockquote><div className={styles.briefRule}/><span className={styles.kicker}>PUT IT INTO PRACTICE</span><p>{quote[1]}</p><span className={styles.scripture}>READ / {quote[2]}</span><small>Scripture reference for reading; the quote is an original reflection.</small></section></div>
        <section className={styles.panel}><div className={styles.panelHead}><h3>TODAY’S MISSION QUEUE</h3><span>{todayMissions.filter(m=>m.done).length} / {todayMissions.length} COMPLETE</span></div>{todayMissions.length?todayMissions.map(missionRow):<div className={styles.empty}><Target size={22}/><p>Your next chapter needs a place on the calendar.</p><span>Add a mission from Build or plan a local experience.</span></div>}<div className={styles.inlineActions}><button onClick={()=>openView('BUILD')}><Plus size={14}/> ADD A BUILD MISSION</button><button onClick={()=>openView('EXPLORE')}><Compass size={14}/> PLAN AN EXPERIENCE</button></div></section>
        {overdue.length>0&&<details className={styles.panel}><summary>{overdue.length} UNFINISHED FROM EARLIER DAYS</summary><p>Choose deliberately: reschedule, finish, or remove. Nothing is marked complete automatically.</p>{overdue.map(m=><div className={styles.agendaRow} key={m.id}><div><span>{m.date}</span><strong>{m.title}</strong></div><button onClick={()=>patchMission(m.id,{date:localDay()})}>MOVE TO TODAY</button></div>)}</details>}
        <section className={styles.panel}><div className={styles.panelHead}><h3>LEAVE ROOM TO LIVE</h3><Compass size={14}/></div>{upcoming.length?upcoming.slice(0,4).map(m=><div className={styles.agendaRow} key={m.id}><div><span>{m.date} {m.time&&`/ ${m.time}`}</span><strong>{m.title}</strong></div><button onClick={()=>{setView('REVIEW');setExpanded(m.id);}}>VIEW</button></div>):<p>Plan one new place or shared experience this week. Give it a day, a budget, and enough time to enjoy it.</p>}<button onClick={()=>openView('EXPLORE')}>EXPLORE LA <ArrowUpRight size={14}/></button></section>
      </>}
      {view==='BUILD'&&<>
        <div className={styles.sectionIntro}><h3>BUILD EVERY DIMENSION.</h3><p>Choose an area, choose an action, produce a result. A focused block beats another hour of scrolling.</p></div><div className={styles.pillarGrid}>{PILLARS.map(p=>{const Icon=ICONS[p.id];return <button key={p.id} aria-pressed={pillar===p.id} onClick={()=>setPillar(p.id)}><Icon size={18}/><span>{p.label}</span><small>{weeklyPillarDays(plan.missions,date,p.id)} DAYS / 7D</small></button>;})}</div><div className={styles.selectionHead}><div><h3>{selected.label}</h3><p>{selected.intent}</p></div><label>TIME AVAILABLE<select value={available} onChange={e=>setAvailable(Number(e.target.value))}>{[5,15,30,60].map(m=><option key={m} value={m}>Up to {m} min</option>)}</select></label></div><div className={styles.ideaGrid}>{suggested.map(idea=>{const added=plan.missions.some(m=>m.sourceId===idea.id&&m.date===date);return <article className={styles.idea} key={idea.id}><div className={styles.ideaMeta}><span>{selected.label}</span><span>{idea.minutes} MIN</span></div><h4>{idea.title}</h4><p>{idea.detail}</p><div className={styles.proof}><span>FINISH LINE</span>{idea.proof}</div><button disabled={added} onClick={()=>addMission(idea)}>{added?<><Check size={14}/> ON TODAY’S PLAN</>:<><Plus size={14}/> ADD TO TODAY</>}</button></article>;})}</div>{!suggested.length&&<p className={styles.empty}>No {selected.label.toLowerCase()} mission fits this time window. Choose a longer block or add your own small step.</p>}<form className={styles.custom} onSubmit={e=>{e.preventDefault();if(!custom.trim())return;if(addMission({id:crypto.randomUUID(),pillar,title:custom.trim(),detail:'Your own mission. Define the result and record it when finished.',minutes:customMinutes,proof:'Your completed result.'}))setCustom('');}}><label>YOUR OWN {selected.label} MISSION<input value={custom} onChange={e=>setCustom(e.target.value)} maxLength={180} required placeholder="Name a concrete action and finish line"/></label><label>MINUTES<input type="number" min={5} max={240} step={5} value={customMinutes} onChange={e=>setCustomMinutes(Number(e.target.value))} required/></label><button type="submit"><Plus size={14}/> ADD</button></form>
      </>}
      {view==='EXPLORE'&&<>
        <div className={styles.sectionIntro}><h3>EXPLORE LA.</h3><p>Dining, outdoors, tourist landmarks, local neighborhoods, and beaches. Pick something that gets you out of the usual loop and put it on the calendar.</p></div><div className={styles.filters}><label>AREA<select value={plan.area} onChange={e=>update(current=>({...current,area:e.target.value}))}>{['All areas','Los Angeles'].map(a=><option key={a}>{a}</option>)}</select></label><label>EXPERIENCE<select value={kind} onChange={e=>setKind(e.target.value)}>{['All types','Dining','Outdoors','Tourist','Local','Beaches'].map(a=><option key={a}>{a}</option>)}</select></label></div><div className={styles.ideaGrid}>{PLACES.filter(p=>(plan.area==='All areas'||p.area===plan.area)&&(kind==='All types'||p.kind===kind)).map(place=><article className={styles.place} key={place.id}><div className={styles.ideaMeta}><span>{place.area.toUpperCase()}</span><span>{place.kind.toUpperCase()}</span></div><h4>{place.title}</h4><p>{place.detail}</p><small>{place.cost}</small><a href={place.url} target="_blank" rel="noopener noreferrer">{place.source} <ArrowUpRight size={13}/></a><button onClick={()=>{setOuting(place);setOutingDate(localDay());setOutingTime('');}}>PLAN THIS EXPERIENCE <Plus size={14}/></button>{outing?.id===place.id&&<form className={styles.outingForm} onSubmit={e=>{e.preventDefault();if(!outingDate)return;if(addMission({id:place.id,pillar:'experiences',title:place.mission,detail:`${place.detail} Check the official site for hours, cost, eligibility and registration. Include travel time.`,minutes:place.minutes,proof:'Went, participated, and noted one thing learned.'},outingDate,outingTime,place.id))setOuting(null);}}><label>DATE<input type="date" min={date} value={outingDate} required onChange={e=>setOutingDate(e.target.value)}/></label><label>TIME (OPTIONAL)<input type="time" value={outingTime} onChange={e=>setOutingTime(e.target.value)}/></label><button type="submit">SAVE TO MY PLAN</button><button type="button" onClick={()=>setOuting(null)}>CANCEL</button></form>}</article>)}</div><div className={styles.fieldRule}><HeartHandshake size={19}/><div><b>SHOW UP WITH CURIOSITY.</b><p>Ask a genuine question, listen, and follow up when welcome. Community grows through repeat visits. Start with free or low-cost options that fit your budget.</p></div></div><p className={styles.footnote}>Use the official link on each place to verify current hours, charges, parking, beach conditions, travel, and reservations before going. Saving a plan does not book or register you.</p>
      </>}
      {view==='REVIEW'&&<>
        <section className={styles.panel}><div className={styles.panelHead}><h3>AFTER-ACTION REVIEW</h3><span>{date}</span></div><p>Record evidence of growth. Completion is feedback, not a measure of your worth.</p>{([['win','WHAT DID I BUILD OR FOLLOW THROUGH ON?'],['lesson','WHAT PULLED ME OFF COURSE? WHAT CHANGES NEXT?'],['tomorrow','TOMORROW’S FIRST MOVE']] as const).map(([key,label])=><label className={styles.reviewField} key={key}>{label}<textarea rows={2} maxLength={1200} value={day[key]} onChange={e=>{const value=e.target.value;changeDay(d=>({...d,[key]:value}));}}/></label>)}</section><section className={styles.panel}><div className={styles.panelHead}><h3>LAST SEVEN DAYS</h3><span>RECORDED ACTIONS</span></div><div className={styles.weekGrid}>{PILLARS.map(p=>{const count=weeklyPillarDays(plan.missions,date,p.id);return <div key={p.id}><span>{p.label}</span><b>{count} / {p.target} days</b><div className={styles.bar}><i style={{width:`${Math.min(100,count/p.target*100)}%`}}/></div></div>;})}</div><small>Suggested targets count distinct days with completed missions. Your priorities and earlier habits remain separate.</small></section><section className={styles.panel}><div className={styles.panelHead}><h3>MISSION HISTORY & PLANS</h3><span>{plan.missions.length} TOTAL</span></div>{plan.missions.length?[...plan.missions].sort((a,b)=>b.date.localeCompare(a.date)).map(m=><div key={m.id}><span className={styles.historyDate}>{m.date}</span>{missionRow(m)}</div>):<p>Your first mission starts your record.</p>}</section><details className={styles.panel}><summary>EARLIER DAILY PLAN & PRIORITY HISTORY</summary>{DAY_BLOCKS.map(block=><label className={styles.legacyBlock} key={block.id}><input type="checkbox" checked={!!day.blocks[block.id]} onChange={()=>changeDay(d=>({...d,blocks:{...d.blocks,[block.id]:!d.blocks[block.id]}}))}/><span>{block.label}<small>{block.action}</small></span></label>)}{Object.entries(plan.days).sort(([a],[b])=>b.localeCompare(a)).slice(0,14).map(([key,entry])=><div className={styles.agendaRow} key={key}><span>{key}</span><span>{entry.priorities.filter(p=>p.done).length}/{entry.priorities.length} priorities · {entry.focusMinutes} min</span></div>)}</details>
      </>}
      <section className={`${styles.panel} ${styles.focusPanel}`} ref={focusRef}><div className={styles.panelHead}><h3><Timer size={14}/> FOCUS CONTROL</h3><span>{plan.session?'SESSION ACTIVE':'READY'}</span></div>{plan.session?<><div className={styles.focusActive}><div><span className={styles.kicker}>CURRENT OBJECTIVE</span><strong>{plan.session.title}</strong></div><div className={styles.timer} role="timer">{String(Math.floor(remaining/60)).padStart(2,'0')}:{String(remaining%60).padStart(2,'0')}</div></div><div className={styles.inlineActions}><button disabled={remaining>0} onClick={()=>endFocus(true)}>{remaining?'IN PROGRESS':'RECORD COMPLETED BLOCK'}</button><button onClick={()=>endFocus(false)}>CANCEL</button></div><small>Record only time you actually focused. The timer does not monitor or block apps.</small></>:<form className={styles.focusForm} onSubmit={e=>{e.preventDefault();const title=focusTitle.trim()||nextTitle;if(title)startFocus(title,focusLength);}}><label>OBJECTIVE<input value={focusTitle} maxLength={180} placeholder={nextTitle} onChange={e=>setFocusTitle(e.target.value)}/></label><label>DURATION<select value={focusLength} onChange={e=>setFocusLength(Number(e.target.value))}>{[5,15,25,50].map(n=><option value={n} key={n}>{n} MIN</option>)}</select></label><button type="submit"><Focus size={14}/> START</button></form>}</section>
      <footer className={styles.footer}><span>CONSISTENCY / RESPONSIBILITY / FAITH</span><small>JARVIS Cloud is the permanent source of truth when signed in; this browser remains a fast local cache.</small></footer>
    </>}
  </div>;
}
